# Legacy routes

legacy_index:
    path: ../

legacy_main:
    path: ../main/{name}
    defaults: {_controller: 'ChamiloCoreBundle:Legacy:classic'}
    requirements:
        name: .+

core_controller:
    resource: '@ChamiloCoreBundle/Controller/IndexController.php'
    type: annotation

userportal:
    resource: '@ChamiloCoreBundle/Controller/UserPortalController.php'
    type: annotation
    prefix: /userportal

sidebar_controller:
    resource: '@ChamiloThemeBundle/Controller/SidebarController.php'
    type: annotation

front:
    resource: '@ChamiloCoreBundle/Controller/FrontController.php'
    type: annotation
    prefix: /front

user:
    resource: '@ChamiloCoreBundle/Controller/User/UserController.php'
    type: annotation
    prefix: /user

course:
    resource: '@ChamiloCoreBundle/Controller/CourseController.php'
    type: annotation
    prefix: /course

legacy_javascript:
    resource: '@ChamiloCoreBundle/Controller/JavascriptLegacyController.php'
    type: annotation
    prefix: /js


legacy_plugin:
    path: /plugin/{name}
    defaults: {_controller: 'ChamiloCoreBundle:Legacy:plugin'}
    requirements:
        name: .+

# web url shortcuts for legacy templates
web.ajax:
    path: main/inc/ajax/

web.main:
    path: main/

# Core controllers
core_admin:
    resource: '@ChamiloCoreBundle/Controller/Admin'
    type: annotation
    prefix: /admin

# Redirects /url/ to /url always located at the end
remove_trailing_slash:
    path: /{url}
    defaults: {_controller: 'ChamiloCoreBundle:Redirecting:removeTrailingSlash'}
    requirements:
        url: .*/$
        _method: GET
