services:
    _defaults:
        autowire: false
        public: true
        autoconfigure: false

    # Tool chain loads the list of tool services with the tag "chamilo_core.tool"
    # Tool chain is filled in file DependencyInjection/Compiler/ToolCompilerClass.php
    Chamilo\CoreBundle\ToolChain: ~

    # Global
    chamilo_core.tool.global:
        class: Chamilo\CoreBundle\Tool\GlobalTool
        arguments:
            - 'global'
            - ''
            - ''
            - ~
            -
                urls:
                    repository: Chamilo\CoreBundle\Repository\Node\AccessUrlRepository
                courses:
                    repository: Chamilo\CoreBundle\Repository\Node\CourseRepository
                users:
                    repository: Chamilo\CoreBundle\Repository\Node\UserRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.asset:
        class: Chamilo\CoreBundle\Tool\Asset
        arguments:
            - 'asset'
            - ''
            - ''
            - ~
            -
                illustrations:
                    repository: Chamilo\CoreBundle\Repository\Node\IllustrationRepository
        tags:
            - {name: chamilo_core.tool}

    # Agenda tool
    chamilo_core.tool.agenda:
        class: Chamilo\CoreBundle\Tool\Agenda
        calls:
            -   setIcon: [ 'mdi-calendar' ]
        arguments:
            - 'agenda'
            - 'authoring'
            - '/main/calendar/agenda.php'
            - '@chamilo_course.settings.agenda'
            -
                events:
                    repository: Chamilo\CourseBundle\Repository\CCalendarEventRepository
                event_attachments:
                    repository: Chamilo\CourseBundle\Repository\CCalendarEventAttachmentRepository
        tags:
            - {name: chamilo_core.tool}

    # Announcement tool
    chamilo_core.tool.announcement:
        class: Chamilo\CoreBundle\Tool\Announcement
        calls:
            - setIcon: [ 'mdi-bullhorn' ]
        arguments:
            - 'announcement'
            - 'authoring'
            - '/main/announcements/announcements.php'
            - '@chamilo_course.settings.announcement'
            -
                announcements:
                    repository: Chamilo\CourseBundle\Repository\CAnnouncementRepository
                announcements_attachments:
                    repository: Chamilo\CourseBundle\Repository\CAnnouncementAttachmentRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.assignment:
        class: Chamilo\CoreBundle\Tool\Assignment
        arguments:
            - 'student_publication'
            - 'interaction'
            - '/main/work/work.php'
            - '@chamilo_course.settings.assignment'
            -
                student_publications:
                    repository: Chamilo\CourseBundle\Repository\CStudentPublicationRepository
                student_publications_assignments:
                    repository: Chamilo\CourseBundle\Repository\CStudentPublicationAssignmentRepository
                student_publications_comments:
                    repository: Chamilo\CourseBundle\Repository\CStudentPublicationCommentRepository
                student_publications_corrections:
                    repository: Chamilo\CourseBundle\Repository\CStudentPublicationCorrectionRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.attendance:
        class: Chamilo\CoreBundle\Tool\Attendance
        arguments:
            - 'attendance'
            - 'authoring'
            - '/main/attendance/index.php'
            - '@chamilo_course.settings.attendance'
            -
                attendances:
                    repository: Chamilo\CourseBundle\Repository\CAttendanceRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.blog:
        class: Chamilo\CoreBundle\Tool\Blog
        arguments:
            - 'blog'
            - 'admin'
            - '/main/blog/blog_admin.php'
            - '@chamilo_course.settings.blog'
            -
                blogs:
                    repository: Chamilo\CourseBundle\Repository\CBlogRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.course_description:
        calls:
            -   setIcon: [ 'mdi-card-text' ]
        class: Chamilo\CoreBundle\Tool\CourseDescription
        arguments:
            - 'course_description'
            - 'authoring'
            - '/main/course_description/index.php'
            - '@chamilo_course.settings.course_description'
            -
                course_descriptions:
                    repository: Chamilo\CourseBundle\Repository\CCourseDescriptionRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.course_tool:
        class: Chamilo\CoreBundle\Tool\CourseTool
        calls:
            -   setIcon: [ 'mdi-file-link' ]
        arguments:
            - 'course_tool'
            - 'admin'
            - '/resources/course_tool/links'
            - ~
            -
                links:
                    repository: Chamilo\CourseBundle\Repository\CToolRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.chat:
        class: Chamilo\CoreBundle\Tool\Chat
        arguments:
            - 'chat'
            - 'interaction'
            - '/resources/chat/'
            - '@chamilo_course.settings.chat'
            -
                conversations:
                    repository: Chamilo\CourseBundle\Repository\CChatConversationRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.course_progress:
        class: Chamilo\CoreBundle\Tool\CourseProgress
        arguments:
            - 'course_progress'
            - 'authoring'
            - '/main/course_progress/index.php'
            - '@chamilo_course.settings.course_progress'
            -
                thematics:
                    repository: Chamilo\CourseBundle\Repository\CThematicRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.document:
        class: Chamilo\CoreBundle\Tool\Document
        calls:
            -   setIcon: [ 'mdi-file-document' ]
        arguments:
            - 'document'
            - 'authoring'
            - '/resources/document/'
            - '@chamilo_course.settings.document'
            -
                files:
                    repository: Chamilo\CourseBundle\Repository\CDocumentRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.dropbox:
        class: Chamilo\CoreBundle\Tool\Dropbox
        calls:
            -   setIcon: [ 'mdi-cloud-upload' ]
        arguments:
            - 'dropbox'
            - 'interaction'
            - '/main/dropbox/index.php'
            - '@chamilo_course.settings.dropbox'
            -
                dropbox:
                    repository: Chamilo\CourseBundle\Repository\CDropboxRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.exercise:
        class: Chamilo\CoreBundle\Tool\Exercise
        arguments:
            - 'quiz'
            - 'authoring'
            - '/main/exercise/exercise.php'
            - '@chamilo_course.settings.exercise'
            -
                exercises:
                    repository: Chamilo\CourseBundle\Repository\CQuizRepository
                questions:
                    repository: Chamilo\CourseBundle\Repository\CQuizQuestionRepository
                question_categories:
                    repository: Chamilo\CourseBundle\Repository\CQuizQuestionCategoryRepository
                exercise_categories:
                    repository: Chamilo\CourseBundle\Repository\CExerciseCategoryRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.forum:
        class: Chamilo\CoreBundle\Tool\Forum
        calls:
            -   setIcon: [ 'mdi-forum' ]
        arguments:
            - 'forum'
            - 'interaction'
            - '/main/forum/index.php'
            - '@chamilo_course.settings.forum'
            -
                forums:
                    repository: Chamilo\CourseBundle\Repository\CForumRepository
                forum_attachments:
                    repository: Chamilo\CourseBundle\Repository\CForumAttachmentRepository
                forum_categories:
                    repository: Chamilo\CourseBundle\Repository\CForumCategoryRepository
                forum_posts:
                    repository: Chamilo\CourseBundle\Repository\CForumPostRepository
                forum_threads:
                    repository: Chamilo\CourseBundle\Repository\CForumThreadRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.glossary:
        class: Chamilo\CoreBundle\Tool\Glossary
        calls:
            - setIcon: [ 'mdi-alphabetical' ]
        arguments:
            - 'glossary'
            - 'authoring'
            - '/main/glossary/index.php'
            - '@chamilo_course.settings.glossary'
            -
                words:
                    repository: Chamilo\CourseBundle\Repository\CGlossaryRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.gradebook:
        calls:
            -   setIcon: [ 'mdi-note-check' ]
        class: Chamilo\CoreBundle\Tool\Gradebook
        arguments:
            - 'gradebook'
            - 'authoring'
            - '/main/gradebook/index.php'
            - '@chamilo_course.settings.gradebook'
            -
                gradebook_categories:
                    repository: Chamilo\CourseBundle\Repository\CGradebookCategoryRepository
                gradebook_links:
                    repository: Chamilo\CourseBundle\Repository\CGradebookLinkRepository
                gradebook_evaluations:
                    repository: Chamilo\CourseBundle\Repository\CGradebookEvaluationRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.group:
        class: Chamilo\CoreBundle\Tool\Group
        calls:
            -   setIcon: [ 'mdi-account-group' ]
        arguments:
            - 'group'
            - 'interaction'
            - '/main/group/group.php'
            - '@chamilo_course.settings.group'
            -
                groups:
                    repository: Chamilo\CourseBundle\Repository\CGroupRepository
                group_categories:
                    repository: Chamilo\CourseBundle\Repository\CGroupCategoryRepository
                gradebook_evaluations:
                    repository: Chamilo\CourseBundle\Repository\CGradebookEvaluationRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.learning_path:
        calls:
            -   setIcon: [ 'mdi-map-marker-path' ]
        class: Chamilo\CoreBundle\Tool\LearningPath
        arguments:
            - 'learnpath'
            - 'authoring'
            - '/main/lp/lp_controller.php'
            - '@chamilo_course.settings.learning_path'
            -
                lps:
                    repository: Chamilo\CourseBundle\Repository\CLpRepository
                lp_categories:
                    repository: Chamilo\CourseBundle\Repository\CLpCategoryRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.link:
        class: Chamilo\CoreBundle\Tool\Link
        calls:
            -   setIcon: [ 'mdi-file-link' ]
        arguments:
            - 'link'
            - 'authoring'
            - '/main/link/link.php'
            - '@chamilo_course.settings.link'
            -
                links:
                    repository: Chamilo\CourseBundle\Repository\CLinkRepository
                link_categories:
                    repository: Chamilo\CourseBundle\Repository\CLinkCategoryRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.member:
        class: Chamilo\CoreBundle\Tool\Member
        calls:
            -   setIcon: [ 'mdi-account' ]
        arguments:
            - 'member'
            - 'interaction'
            - '/main/user/user.php'
            - '@chamilo_course.settings.user'
            - ~
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.maintenance:
        class: Chamilo\CoreBundle\Tool\Maintenance
        arguments:
            - 'course_maintenance'
            - 'admin'
            - '/main/course_info/maintenance.php'
            - '@chamilo_course.settings.maintenance'
            - ~
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.notebook:
        class: Chamilo\CoreBundle\Tool\Notebook
        arguments:
            - 'notebook'
            - 'interaction'
            - '/main/notebook/index.php'
            - '@chamilo_course.settings.notebook'
            -
                notebooks:
                    repository: Chamilo\CourseBundle\Repository\CNotebookRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.settings:
        class: Chamilo\CoreBundle\Tool\Settings
        arguments:
            - 'course_setting'
            - 'admin'
            - '/main/course_info/infocours.php'
            - '@chamilo_course.settings.settings'
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.shortcut:
        class: Chamilo\CoreBundle\Tool\Shortcut
        arguments:
            - 'shortcut'
            - ''
            - ''
            -  ~
            -
                shortcuts:
                    repository: Chamilo\CourseBundle\Repository\CShortcutRepository
                external_tools:
                    repository: Chamilo\LtiBundle\Repository\ExternalToolRepository
        tags:
            - {name: chamilo_core.tool}

    # Survey
    chamilo_core.tool.survey:
        class: Chamilo\CoreBundle\Tool\Survey
        calls:
            -   setIcon: [ 'mdi-file-question' ]
        arguments:
            - 'survey'
            - 'interaction'
            - '/main/survey/survey_list.php'
            - '@chamilo_course.settings.survey'
            -
                surveys:
                    repository: Chamilo\CourseBundle\Repository\CSurveyRepository
                survey_questions:
                    repository: Chamilo\CourseBundle\Repository\CSurveyQuestionRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.tracking:
        class: Chamilo\CoreBundle\Tool\Tracking
        calls:
            -   setIcon: [ 'mdi-chart-bar' ]
        arguments:
            - 'tracking'
            - 'interaction'
            - '/main/tracking/courseLog.php'
            - '@chamilo_course.settings.tracking'
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.user:
        class: Chamilo\CoreBundle\Tool\User
        arguments:
            - 'user'
            - 'interaction'
            - '/resources/user/'
            - ~
            -
                files:
                    repository: Chamilo\CoreBundle\Repository\Node\PersonalFileRepository
                message_attachments:
                    repository: Chamilo\CoreBundle\Repository\Node\MessageAttachmentRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.usergroup:
        class: Chamilo\CoreBundle\Tool\UserGroup
        arguments:
            - 'usergroup'
            - ''
            - '/resources/usergroup/'
            - ~
            -
                usergroups:
                    repository: Chamilo\CoreBundle\Repository\Node\UsergroupRepository
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.wiki:
        class: Chamilo\CoreBundle\Tool\Wiki
        arguments:
            - 'wiki'
            - 'interaction'
            - '/main/wiki/index.php'
            - '@chamilo_course.settings.wiki'
            -
                wikis:
                    repository: Chamilo\CourseBundle\Repository\CWikiRepository
        tags:
            - {name: chamilo_core.tool}
