a2lix_translation_form:
    locale_provider: default       # [1]
    locales: [en, fr, es, de]          # [1-a]
    default_locale: en             # [1-b]
    required_locales: [en]         # [1-c]
    templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"      # [3]
