services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: true
        bind:
            $passwordEncrypt: '%password_encryption%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AdminBundle\:
        resource: '../../src/AdminBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AdminBundle/{ChamiloAdminBundle.php,Entity,Repository,Tests}'

    ClassificationBundle\:
        resource: '../../src/ClassificationBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/ClassificationBundle/{ChamiloClassificationBundle.php,Entity,Admin,Document,Repository,Tests}'

    ContactBundle\:
        resource: '../../src/ContactBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/ContactBundle/{ChamiloContactBundle.php,Entity,Admin,Controller,DependencyInjection,Form,Repository,Tests}'

    Chamilo\CoreBundle\:
        resource: '../../src/CoreBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/CoreBundle/{Admin,Block,Component,Composer,DependencyInjection,EventListener,Form,Framework,Menu,Migrations,Security,Settings,Twig,Controller,ChamiloCoreBundle.php,Entity,Repository,Tests}'

    Chamilo\CoreBundle\Controller\:
        resource: '../../src/CoreBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    Chamilo\UserBundle\:
        resource: '../../src/UserBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/UserBundle/{Admin,ChamiloUserBundle.php,Security/FOSUBUserProvider.php,DependencyInjection,Form,EventListener,Entity,Repository}'

    chamilo_lti_utils:
        class: Chamilo\LtiBundle\Util\Utils
        arguments: ['@chamilo.settings.manager']

# Doctrine audit
sonata_doctrine_orm_admin:
    audit:
        force: false # Audits are set in the admin.yml files with audit:true

# Grid default template
#apy_data_grid:
#    theme: ChamiloCoreBundle::grid.html.twig
#

# Platform settings (new)
sylius_settings:
    driver: doctrine/orm

# Course settings
chamilo_course:
    driver: doctrine/orm
#    resources:
#        parameter:
#            classes:
#                model: Chamilo\CourseBundle\Entity\CCourseSetting
#                repository: Chamilo\CourseBundle\Repository\CCourseSettingRepository

doctrine_cache:
    providers:
        sylius_settings:
            type: file_system
        chamilo_settings:
            type: file_system

gregwar_captcha:
    width: 200
    height: 50
    length: 6

imports:
    - {resource: ../../src/CoreBundle/Resources/config/services.yml}
    - {resource: ../../src/PageBundle/Resources/config/services.yml}
    - {resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml}
