fm_elfinder:
    assets_path: /chamilo_master/public/assets
    instances:
        default:
            locale: '%locale%' # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
#                    uploads:
#                        show_hidden: false # defaults to false
#                        driver: LocalFileSystem
#                        path: uploads
#                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
#                        upload_deny: ['all']
#                        upload_max_size: 2M
                    local:
                        driver: Flysystem
                        path: uploads
                        flysystem:
                            type: local
                            options:
                                local:
                                    path: '%kernel.root_dir%/../public/uploads/media/'
                        upload_allow: ['all']
                        #upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        #upload_deny: ['all']
                        upload_max_size: 2M
