fos_user:
    db_driver: orm
    firewall_name: admin
    user_class: Chamilo\UserBundle\Entity\User

    group:
        group_class: Chamilo\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

    from_email:
        address: 'test@example.com'
        sender_name: 'test@example.com'
