framework:
    form: true
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #esi: ~
    #fragments: ~
    php_errors:
        log: true
    templating:
        engines: ['twig', 'php']
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.native_file
        name: chamilo2
    fragments: ~
    http_method_override: true
    annotations: true
