# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        resource:
            #frontend: dropzone # or any uploader you use in the frontend
            #frontend: blueimp
            frontend: custom
            storage:
                type: flysystem
                filesystem: oneup_flysystem.resources_filesystem
            root_folder: true
            custom_frontend:
                class: 'Chamilo\CoreBundle\Controller\ResourceUploadController'
                name: upload

#            namer: oneup_uploader.namer.urlsafe
