translation:
    locales: ["en"]
    edit_in_place:
        enabled: true
        config_name: app
        #activator: php_translation.edit_in_place.activator
    configs:
        app:
            dirs: ["%kernel.project_dir%/var/templates", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/src/CoreBundle/Resources/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
