symfonycasts_reset_password:
    request_password_repository: Chamilo\CoreBundle\Repository\ResetPasswordRequestRepository
    lifetime: 3600
    throttle_limit: 3600
    enable_garbage_collection: true
