framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
            - '%kernel.project_dir%/src/CoreBundle/Resources/translations'
        fallbacks:
            - '%locale%'
