twig:
    debug: '%kernel.debug%'
    paths: ['%kernel.project_dir%/templates', '%kernel.project_dir%/main/template/', '%kernel.project_dir%/plugin/']
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
        - '@SonataCore/Form/color.html.twig'
    exception_controller: 'Chamilo\ThemeBundle\Controller\ExceptionController::showAction'
    globals:
        show_toolbar: true
        show_footer: true
        software_name: Chamilo
        version: 2
        messages_count:
        message_link:
        execution_stats:
        course_session_block:
        show_course_shortcut:
        show_course_navigation_menu:
        actions:
        header:
        message:
        show_media_element: 1
        footer_extra_content:
