vich_uploader:
    db_driver: orm
    storage: flysystem
    twig: true
    mappings:
        resources:
            uri_prefix: ''
            upload_destination: oneup_flysystem.resource_filesystem
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
                options: {chars_per_dir: 1, dirs: 3} # will create directory "a/b/c" for "abcdef.jpg"
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        assets:
            uri_prefix: ''
            upload_destination: oneup_flysystem.asset_filesystem
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Chamilo\CoreBundle\Component\Utils\AssetDirectoryNamer
                options: {property: 'category'}
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
