chamilo_course:
    resource: "@ChamiloCourseBundle/Resources/config/routing.yml"
    prefix: /
    options:
        expose: true

chamilo_contact:
    resource: "@ChamiloContactBundle/Resources/config/routing.yml"
    prefix: /contact

chamilo_user:
    resource: "@ChamiloUserBundle/Resources/config/routing.yml"
    prefix: /
    options:
        expose: true

# Always at the end
chamilo_core:
    resource: "@ChamiloCoreBundle/Resources/config/routing.yml"
    options:
        expose: true

chamilo_page:
    resource: "@ChamiloPageBundle/Resources/config/routing.yml"

chamilo_faq:
    resource: "@ChamiloFaqBundle/Resources/config/routing.yml"

chamilo_graphql:
    resource: "@ChamiloGraphQlBundle/Resources/config/routing.yaml"

chamilo_lti:
    resource: "@ChamiloLtiBundle/Resources/config/routing.yml"
