assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:      %kernel.root_dir%/../web
    write_to:       %kernel.root_dir%/../web
    bundles:        [ChamiloCoreBundle]

    filters:
        cssrewrite: ~
        yui_js:  { jar: "%kernel.root_dir%/../bin/yuicompressor.jar" }
        yui_css: { jar: "%kernel.root_dir%/../bin/yuicompressor.jar" }

    assets:
#        chamilo_bootstrap_css:
#            inputs:
#                - bundles/chamilocore/components/bootstrap/dist/css/bootstrap.min.css
#            filters:
#                - cssrewrite
#        chamilo_font_awesome_css:
#            inputs:
#                - bundles/chamilocore/components/fontawesome/css/font-awesome.min.css
#            filters:
#                - cssrewrite
#        chamilo_ionicons_css:
#            inputs:
#                - bundles/chamilocore/components/ionicons/css/ionicons.css
#            filters:
#                - cssrewrite
#
#        chamilo_css:
#            inputs:
#                - @chamilo_bootstrap_css
#                - @chamilo_font_awesome_css
#                - @chamilo_ionicons_css
#                - bundles/chamilocore/components/fullcalendar/dist/fullcalendar.min.css
#                - bundles/chamilocore/components/chosen-bower/chosen.css
#                - bundles/chamilocore/components/jquery-ui/themes/cupertino/jquery-ui.min.css
#                - bundles/chamilocore/components/bootflat/css/bootflat.css
#                - bundles/chamilocore/components/jqgrid/css/ui.jqgrid.css
#                - bundles/chamilocore/components/select2/dist/css/select2.css
#                - bundles/chamilocore/js/tag/style.css
#                - bundles/chamilocore/components/jquery-file-upload/css/jquery.fileupload.css
#                - bundles/chamilocore/components/jquery-file-upload/css/jquery.fileupload-ui.css
#                - bundles/chamilocore/components/bootstrap-language/languages.css
#                - bundles/chamilocore/css/grid.css
#
##                - bundles/chamilocore/components/select2/select2-bootstrap.css
##                - bundles/chamilocore/components/adminlte/css/jvectormap/*
##                - bundles/chamilocore/components/adminlte/css/morris/*
##                - bundles/chamilocore/components/adminlte/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.css
##                - bundles/chamilocore/components/adminlte/css/bootstrap-slider/slider.css
##                - bundles/chamilocore/components/adminlte/css/colorpicker/bootstrap-colorpicker.css
##                - bundles/chamilocore/components/adminlte/css/datatables/dataTables.bootstrap.css
##                - bundles/chamilocore/components/adminlte/css/daterangepicker/daterangepicker-bs3.css
##                - bundles/chamilocore/components/adminlte/css/iCheck/all.css
##                - bundles/chamilocore/components/adminlte/css/ionslider/ion.rangeSlider.css
##                - bundles/chamilocore/components/adminlte/css/timepicker/bootstrap-timepicker.css
#                - bundles/chamilocore/components/bootstrap-daterangepicker/daterangepicker-bs3.css
#                - bundles/chamilocore/components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css
#                - bundles/chamilocore/components/adminlte/dist/css/skins/_all-skins.min.css
#                - bundles/chamilocore/components/adminlte/dist/css/AdminLTE.css
#            filters:
#                - cssrewrite
#            output: js/chamilo.css
#
#        chamilo_js:
#            inputs:
#                - bundles/chamilocore/components/jquery/dist/jquery.js
#                - bundles/chamilocore/components/jquery-ui/jquery-ui.min.js
##                - @bootstrap_js
#                - bundles/chamilocore/components/bootstrap/dist/js/bootstrap.min.js
#                - bundles/chamilocore/components/chosen-bower/chosen.jquery.js
##                - @moment_js
#                - bundles/chamilocore/components/moment/moment.js
#                - bundles/chamilocore/components/fullcalendar/dist/fullcalendar.min.js
#                - bundles/chamilocore/components/jqgrid/js/jquery.jqGrid.js
#                - bundles/chamilocore/components/select2/dist/js/select2.js
#                - bundles/chamilocore/components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
#                - bundles/chamilocore/components/jquery.scrollbar/jquery.scrollbar.js
#                - bundles/chamilocore/components/mediaelement/build/mediaelement-and-player.js
#                - bundles/chamilocore/js/upload.js
#                - bundles/chamilocore/components/image-map-resizer/js/imageMapResizer.js
#
#                - bundles/chamilocore/components/blueimp-load-image/js/load-image.all.min.js
#                - bundles/chamilocore/components/blueimp-canvas-to-blob/js/canvas-to-blob.min.js
#
#                - bundles/chamilocore/js/tag/jquery.fcbkcomplete.js
#
#                - bundles/chamilocore/components/jquery-file-upload/js/jquery.iframe-transport.js
#                - bundles/chamilocore/components/jquery-file-upload/js/jquery.fileupload.js
#                - bundles/chamilocore/components/jquery-file-upload/js/jquery.fileupload-process.js
#                - bundles/chamilocore/components/jquery-file-upload/js/jquery.fileupload-image.js
#                - bundles/chamilocore/components/jquery-file-upload/js/jquery.fileupload-audio.js
#                - bundles/chamilocore/components/jquery-file-upload/js/jquery.fileupload-video.js
#                - bundles/chamilocore/components/jquery-file-upload/js/jquery.fileupload-validate.js
#                - bundles/chamilocore/components/bootstrap-daterangepicker/daterangepicker.js
#                - bundles/chamilocore/components/adminlte/dist/js/app.js
#
#            output: js/chamilo.js


        # see https://sonata-project.org/blog/2012/5/15/assetic-package-configuration
        #
        sonata_jqueryui_js:
            inputs:
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.core.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.widget.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.mouse.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.draggable.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.droppable.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.resizable.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.selectable.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.sortable.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.accordion.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.autocomplete.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.button.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.datepicker.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.dialog.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-blind.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-bounce.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-clip.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-drop.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-explode.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-fade.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-fold.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-highlight.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-pulsate.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-scale.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-shake.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-slide.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-transfer.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.menu.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.position.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.progressbar.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.slider.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.spinner.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.tabs.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.tooltip.js
  #                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/i18n/jquery-ui-i18n.js

#            filters:
#                - yui_js

        sonata_jqueryui_css:
            inputs:
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css

            filters:
                - cssrewrite
#                - yui_css

        sonata_formatter_js:
            inputs:
                # do not uncomment this, ckeditor behave badly when compacted...
                #- %kernel.root_dir%/../web/bundles/sonataformatter/vendor/ckeditor/ckeditor.js
                - %kernel.root_dir%/../web/bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/markdown/set.js
                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/html/set.js
                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/textile/set.js

#            filters:
#                - yui_js

        sonata_formatter_css:
            inputs:
                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/skins/sonata/style.css
                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/markdown/style.css
                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/html/style.css
                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/textile/style.css

            filters:
                - cssrewrite
#                - yui_css

        sonata_admin_js:
            inputs:
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/jquery/dist/jquery.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/moment/min/moment.min.js
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.js
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jquery-form/jquery.form.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/jquery/jquery.confirmExit.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.js
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/select2/select2.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/iCheck/icheck.min.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/slimScroll/jquery.slimscroll.min.js
                - %kernel.root_dir%/../web/bundles/sonatapage/sonata-page.back.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/Admin.js
                - %kernel.root_dir%/../web/bundles/sonataadmin/treeview.js

#            filters:
#                - yui_js

        sonata_admin_css:
            inputs:
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.css
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/themes/flick/jquery-ui.min.css
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/select2/select2.css
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/select2/select2-bootstrap.css
                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
                - %kernel.root_dir%/../web/bundles/sonataadmin/css/styles.css
                - %kernel.root_dir%/../web/bundles/sonataadmin/css/layout.css
                - %kernel.root_dir%/../web/bundles/sonataadmin/css/tree.css
                - %kernel.root_dir%/../web/bundles/sonatapage/sonata-page.back.css

            filters:
                - cssrewrite
#                - yui_css

        sonata_front_js:
            inputs:
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/jquery/dist/jquery.js
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.js
#                - %kernel.root_dir%/../web/bundles/sonataproduct/js/product.js
                - %kernel.root_dir%/../web/bundles/sonatacore/js/base.js
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/select2/select2.min.js
#                - %kernel.root_dir%/../web/bundles/sonatademo/js/demo.js

#            filters:
#                - yui_js

        sonata_front_css:
            inputs:
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
                - %kernel.root_dir%/../web/bundles/sonatacore/vendor/select2/select2.css
#                - %kernel.root_dir%/../web/bundles/mopabootstrap/css/datepicker.css
#                - %kernel.root_dir%/../web/bundles/sonatademo/css/demo.css

            filters:
                - cssrewrite
#                - yui_css
